/**
 * Manual Content Generation System
 * 
 * This file contains pre-written, high-quality content templates
 * for all city pages. No AI API needed!
 * 
 * Content is generated by combining templates with local data.
 */

interface CityData {
    name: string;
    state: string;
    stateAbbr: string;
    population: number;
    electricityRate: number;
    avgInstallCost: number;
    incentives: string[];
}

interface GeneratedContent {
    intro: string;
    faq: Array<{ question: string; answer: string }>;
}

/**
 * Generate unique introduction for a city
 */
export function generateCityIntro(city: CityData): string {
    const templates = [
        // Template 1: Focus on growing EV adoption
        `Installing an EV charger at your ${city.name} home has never been more important. With electric vehicle adoption growing rapidly across ${city.state}, more than ${city.population.toLocaleString()} residents in ${city.name} are making the switch to cleaner transportation. The average cost to install a Level 2 home charging station in ${city.name} is approximately $${city.avgInstallCost.toLocaleString()}, which includes professional installation by a licensed electrician.

With local electricity rates at $${city.electricityRate.toFixed(2)} per kWh, charging your EV at home is both convenient and cost-effective compared to public charging stations. A full charge for a typical 60 kWh battery costs around $${(city.electricityRate * 60).toFixed(2)}, making home charging 50-70% cheaper than using commercial charging networks.

${city.incentives.length > 0 ? `${city.state} residents can take advantage of several incentives to reduce installation costs, including ${city.incentives[0]}. Combined with the federal tax credit of up to $1,000, you could save significantly on your upfront investment.` : 'Federal tax credits of up to $1,000 are available to help offset installation costs, making now an excellent time to install your home charger.'} This guide will walk you through everything you need to know about installing an EV charger in ${city.name}.`,

        // Template 2: Focus on convenience and savings
        `As ${city.name} joins the electric vehicle revolution, homeowners across ${city.state} are discovering the convenience of charging at home. Whether you drive a Tesla, Chevrolet Bolt, Ford Mustang Mach-E, or any other electric vehicle, installing a Level 2 home charger is the smartest investment you can make for your EV ownership experience.

The typical installation cost in ${city.name} ranges around $${city.avgInstallCost.toLocaleString()}, covering both the charging equipment and professional installation. This one-time investment pays for itself through the convenience of never needing to visit public charging stations and the significant savings on fuel costs. With ${city.name}'s electricity rate of $${city.electricityRate.toFixed(2)} per kWh, you'll spend approximately $${(city.electricityRate * 60 * 12).toFixed(2)} per month charging your vehicle at home, compared to $150-200 at public stations.

${city.incentives.length > 0 ? `Residents of ${city.name} can access multiple rebate programs, including ${city.incentives[0]}, which can reduce your installation costs by hundreds or even thousands of dollars.` : 'The federal Alternative Fuel Vehicle Refueling Property Credit provides up to $1,000 for residential EV charger installations.'} Our comprehensive guide will help you find qualified electricians in ${city.name}, understand local permit requirements, and maximize available incentives.`,

        // Template 3: Focus on technical details
        `Planning to install an EV charger in ${city.name}, ${city.state}? You're making a smart choice for both your wallet and the environment. Home EV charging is the most convenient and economical way to keep your electric vehicle powered up and ready to go. In ${city.name}, the average installation cost is $${city.avgInstallCost.toLocaleString()}, which typically includes a Level 2 charging station (capable of adding 25-30 miles of range per hour) and professional installation by a licensed electrician.

Your home's electrical system will need to support the charger, usually requiring a dedicated 240-volt circuit similar to what powers your electric dryer or oven. Most ${city.name} homes can accommodate this without major electrical panel upgrades, though your electrician will assess your specific situation. At ${city.name}'s current electricity rate of $${city.electricityRate.toFixed(2)} per kWh, you'll enjoy significantly lower operating costs compared to gasoline vehicles.

${city.incentives.length > 0 ? `Take advantage of available incentives in ${city.state}, including ${city.incentives[0]}, to reduce your upfront costs.` : 'Federal tax credits can help offset up to $1,000 of your installation costs.'} This guide covers everything from choosing the right charger to finding licensed installers in ${city.name} and navigating the permit process.`
    ];

    // Select template based on city name hash for variety
    const templateIndex = city.name.length % templates.length;
    return templates[templateIndex];
}

/**
 * Generate FAQ for a city
 */
export function generateCityFAQ(city: CityData): Array<{ question: string; answer: string }> {
    return [
        {
            question: `How much does it cost to install an EV charger in ${city.name}, ${city.state}?`,
            answer: `The average cost to install a Level 2 EV charger in ${city.name} is approximately $${city.avgInstallCost.toLocaleString()}. This includes the charging equipment ($400-$800) and professional installation by a licensed electrician ($600-$1,500). Your final cost may vary based on your home's electrical panel capacity, the distance from the panel to your charging location, and whether any electrical upgrades are needed. Most installations in ${city.name} are completed in 2-4 hours.`
        },
        {
            question: `What incentives and rebates are available in ${city.state} for EV charger installation?`,
            answer: city.incentives.length > 0
                ? `${city.state} residents have access to several incentive programs to reduce installation costs. These include ${city.incentives.slice(0, 2).join(' and ')}. Additionally, the federal Alternative Fuel Vehicle Refueling Property Credit offers up to $1,000 (30% of installation costs) for residential EV charger installations. These incentives can be combined, potentially saving you $1,000-$3,000 on your total installation cost.`
                : `While ${city.state} may not currently offer specific state-level incentives, ${city.name} residents can still claim the federal Alternative Fuel Vehicle Refueling Property Credit, which provides up to $1,000 (30% of installation costs) for residential EV charger installations. Check with your local utility company, as many offer rebates or special electricity rates for EV owners that aren't widely advertised.`
        },
        {
            question: `Do I need a permit to install an EV charger in ${city.name}?`,
            answer: `Yes, most EV charger installations in ${city.name} require an electrical permit from your local building department. This is a standard requirement across ${city.state} to ensure the installation meets electrical codes and safety standards. The good news is that your licensed electrician will typically handle the permit application process for you as part of their service. Permit fees in ${city.name} usually range from $50-$150, and inspections are generally quick and straightforward for standard installations.`
        },
        {
            question: `How long does it take to install an EV charger in ${city.name}?`,
            answer: `Most residential EV charger installations in ${city.name} take 2-4 hours to complete. However, the timeline can vary depending on several factors: the distance from your electrical panel to the installation location, whether your panel has available capacity or needs upgrading, and local permit processing times. Simple installations where the charger is mounted near the electrical panel can be completed in as little as 2 hours. More complex installations requiring panel upgrades or long wire runs may take a full day. Your electrician will provide a specific timeline after assessing your home.`
        },
        {
            question: `What's the cost to charge an EV at home in ${city.name}?`,
            answer: `With ${city.name}'s average residential electricity rate of $${city.electricityRate.toFixed(2)} per kWh, charging a typical electric vehicle at home is very affordable. For a vehicle with a 60 kWh battery (like a Tesla Model 3 or Chevy Bolt), a full charge from empty costs approximately $${(city.electricityRate * 60).toFixed(2)}. Most EV owners charge 2-3 times per week, resulting in monthly charging costs of around $${(city.electricityRate * 60 * 12).toFixed(2)}, compared to $150-200 for gasoline. Many ${city.state} utilities also offer special time-of-use rates for EV owners, allowing you to charge overnight at even lower rates.`
        },
        {
            question: `What type of EV charger should I install in my ${city.name} home?`,
            answer: `For most ${city.name} homeowners, a Level 2 charger (240-volt) is the best choice. These chargers add 25-30 miles of range per hour, allowing you to fully charge overnight. Popular brands include ChargePoint Home Flex, JuiceBox, Grizzl-E, and Tesla Wall Connector. When choosing a charger, consider: (1) Amperage - 40-50 amp chargers are most common, (2) Cable length - ensure it reaches your parking spot with room to spare, (3) Smart features - WiFi connectivity for monitoring and scheduling, and (4) Weather resistance - especially important for outdoor installations in ${city.state}. Your electrician can help you select the right model for your specific vehicle and home setup.`
        },
        {
            question: `Can I install an EV charger myself, or do I need an electrician in ${city.name}?`,
            answer: `While some EV charger manufacturers sell "plug-in" models, we strongly recommend hiring a licensed electrician in ${city.name} for installation. Here's why: (1) ${city.state} electrical codes require permits for most installations, (2) Improper installation can create fire hazards and void your home insurance, (3) Many incentive programs require professional installation to qualify, and (4) Licensed electricians ensure your home's electrical system can safely handle the additional load. Professional installation also typically includes a warranty on the work. The peace of mind and safety are well worth the installation cost.`
        },
        {
            question: `Will installing an EV charger increase my home's value in ${city.name}?`,
            answer: `Yes! As electric vehicle adoption grows in ${city.name} and across ${city.state}, homes with installed EV chargers are becoming increasingly attractive to buyers. Studies show that homes with EV charging infrastructure can sell for 2-5% more than comparable homes without them. Beyond resale value, an EV charger is a practical upgrade that makes your home more future-proof. With major automakers committing to electric vehicles and ${city.state} supporting EV adoption, having a charger installed positions your ${city.name} home as move-in ready for the growing number of EV owners.`
        }
    ];
}

/**
 * Generate content for a batch of cities
 */
export function generateBatchContent(cities: CityData[]): Map<string, GeneratedContent> {
    const results = new Map<string, GeneratedContent>();

    for (const city of cities) {
        const intro = generateCityIntro(city);
        const faq = generateCityFAQ(city);

        results.set(`${city.name}-${city.stateAbbr}`, {
            intro,
            faq,
        });
    }

    return results;
}

/**
 * Get content for a single city
 */
export function getCityContent(city: CityData): GeneratedContent {
    return {
        intro: generateCityIntro(city),
        faq: generateCityFAQ(city),
    };
}
